Resources:
  messagesQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 345600
      QueueName: ${self:provider.environment.SQS_MESSAGES_QUEUE}
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 300
